<a href="https://colab.research.google.com/github/syefinfazri/IrisClassfier/blob/main/Multi_Channel_Sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

In [46]:
df = pd.read_excel('Smartphone_By_Shopee___1078675205.xlsx')
df.head()

,Nama Barang,Harga Barang,Lokasi Toko
0,[EXCLUSIVE LAUNCH] HONOR X9C (12/256GB) 108 MP...,Rp4.599.000,Kab. Tangerang
1,Xiaomi Redmi A5 (4+4GB*/128GB) | Kamera hebat ...,Rp1.199.000,Jakarta Utara
2,Tecno Camon 40 8GB 256 GB Garansi Resmi,Rp2.815.000,Jakarta Utara
3,DZL - INFINIX Note 50 4G 8/256 GB NFC Helio G1...,Rp2.649.000,Kab. Sleman
4,POCO X7 5G | Dimensity 7300-Ultra | CrystalRes...,Rp3.799.000,Jakarta Utara

In [49]:
data = {'Harga Barang': ['Rp4.599.000', 'Rp1.199.000', 'Rp2.815.000', 'Rp2.649.000']}
df = pd.DataFrame(data)

df['Harga Barang'] = df['Harga Barang'].str.replace('Rp', '', regex=False)
df['Harga Barang'] = df['Harga Barang'].str.replace('.', '', regex=False)
df['Harga Barang'] = df['Harga Barang'].astype(int)

X = df.drop(['Harga Barang'], axis=1)
y = df['Harga Barang']

print("X:")
print(X)
print("\ny:")
print(y)
print(df_encoded)

X:
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

y:
0    4599000
1    1199000
2    2815000
3    2649000
Name: Harga Barang, dtype: int64
   Harga Barang_Rp1.199.000  Harga Barang_Rp2.649.000  \
0                     False                     False
1                      True                     False
2                     False                     False
3                     False                      True

   Harga Barang_Rp2.815.000  Harga Barang_Rp4.599.000
0                     False                      True
1                     False                     False
2                      True                     False
3                     False                     False

In [57]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [58]:
print("Data Latih:")
print(X_train)

Data Latih:
Empty DataFrame
Columns: []
Index: [3, 0, 2]